### ISSUE TITLE
Layer Startup/Overhead Question

### ISSUE THREAD

**Issue by justinrcs** [iopipe/serverless-newrelic-lambda-layers#14]
Apologies if this is the wrong place to ask this, but I couldn't find any specific support/repo for the New Relic Lambda Layer itself.
We're seeing 6-7 second startup time for the cold-start layer initialization for our Lambda functions when the layer is applied.  From CloudWatch logs:
 

> 08:58:15 Cross application tracing is explicitly disabled in serverless_mode.
> 08:58:15 The native-metrics module is disabled by default when serverless_mode is enabled. If desired, enable the native-metrics module via config file or environment variable.
> 08:58:15 Using New Relic for Node.js. Agent version: 6.1.0; Node version: v10.17.0.
> 08:58:15 Agent state changed from stopped to starting.
> 08:58:15 New Relic for Node.js starting in serverless mode -- skipping connection process
> 08:58:15 START RequestId: 29b543f9-6c19-416c-a30a-a4e2267be9a1 Version: $LATEST
> **08:58:21** entering RaptorContentManagementAPI-dev-initializeDownload

Compare this to the same function when the layer is not applied:

> 19:57:53 START RequestId: 28b48b3d-e44c-40a1-be9e-a4ef326d621e Version: $LATEST
> 19:57:53 entering RaptorContentManagementAPI-dev-initializeDownload

Memory for this function is set to: 320 MB, prior to applying the layer it was 256 MB

Questions:
1. Is this expected behavior?
2. Are there any tuning parameters we can use?
3. What is the recommended memory requirements for instrumentation?

**Comment by kolanos** [comment]
@justinrcs Thanks for reporting this issue. This plugin (and the layer) for Node.js deploys this agent: https://github.com/newrelic/node-newrelic

This is a known issue and is being investigated. However, if you create an issue in that repo it will have more visibility for the Node.js agent team. Going to close this issue as there's nothing in the plugin resulting in this cold start issue. But if you do create an issue in that repo, please link back here so that other users who may be having similar issues can find it.

**Comment by justinrcs** [comment]
Got it - thanks.
Link to issue: [https://github.com/newrelic/node-newrelic/issues/314](https://github.com/newrelic/node-newrelic/issues/314)
